name: first action

on:
  pull_request:
    branches:
      - main
      - develop          
  workflow_dispatch:
  schedule:
      - cron: '0 1 * * *' #Run everyday at 01 AM UTC

jobs:
  build:
    runs-on: server-mm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set branch context
        run: |
          echo "Triggered by branch: ${{ github.ref_name }}"

      - name: Different behavior based on trigger and branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Running for a PR on branch ${{ github.head_ref }}"
          elif [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Running on schedule for branch main"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual trigger by user on branch ${{ github.ref_name }}"
          fi
      
      - name: Save Raw Test Results
        run: |
            echo '[{"name": "Test1", "status": "passed"}, {"name": "Test2", "status": "failed"}, {"name": "Test3", "status": "skipped"}]' > test-results.json
  
      - name: Summarize Test Results
        run: |
            total=$(jq '. | length' test-results.json)
            passed=$(jq '[.[] | select(.status=="passed")] | length' test-results.json)
            failed=$(jq '[.[] | select(.status=="failed")] | length' test-results.json)
            skipped=$(jq '[.[] | select(.status=="skipped")] | length' test-results.json)
  
            echo "### Test Summary" >> $GITHUB_STEP_SUMMARY
            echo "| Total | Passed | Failed | Skipped |" >> $GITHUB_STEP_SUMMARY
            echo "|-------|--------|--------|---------|" >> $GITHUB_STEP_SUMMARY
            echo "| $total | $passed | $failed | $skipped |" >> $GITHUB_STEP_SUMMARY

            # Export the failed count for use in subsequent steps
            echo "FAILED_TESTS=$failed" >> $GITHUB_ENV            

      - name: Fail if too many tests failed
        if: env.FAILED_TESTS > 1
        run: |
            echo "Build failed because more than 1 test failed."
            exit 1  