name: Notify

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string

jobs:
  notify:
    runs-on: server-mm
    environment: 
      name: testing
    steps:
      - name: Mattermost notification
        run: |
          echo "Workflow completed with status: ${{ inputs.status }}."
      - name: Notify Mattermos
        env: 
          ZOHO_PASS_VAR: ${{ secrets.ZOHO_PASS }}
          ZOHO_USER: ${{ vars.ZOHO_USERNAME }}
          MIGUEL_VAR: ${{ secrets.miguel }}
        run: echo "Send $MIGUEL_VAR ing  ${{ secrets.miguel }} Mattermost notification $ZOHO_USER and $ZOHO_PASS_VAR ..."

      - name: Email Zoho notification
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: ${{ vars.ZOHO_SMTP_SERVER }}
          smtp-port: ${{ vars.ZOHO_SMTP_PORT }}
          smtp-secure: true
          from-email: ${{ vars.ZOHO_EMAIL_ADDRESS }}
          to-email: miguel.miranda@sapo.pt,mianpimi@gmail.com
          username: ${{ vars.ZOHO_USERNAME }}
          password: ${{ secrets.ZOHO_PASS }}
          subject: Test Subject
          body: |
            This is a description Build ${{ github.run_id }} for ${{ github.repository }} has completed with ${{ inputs.status }}.
            Another description   ${{ inputs.status }}         
