name: Notify

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string

jobs:
  notify:
    runs-on: server-mm
    steps:
      - name: Notify
        run: |
          echo "Workflow completed with status: ${{ inputs.status }}."
      - name: Notify Mattermost
        run: echo "Sending Mattermost notification..."

